-- ════════════════════════════════════════════════════════════════════
-- ICEKEY — Catalog expansion Part 3: Earrings, Rings, Anklets, Watches
-- Watches: different supplier needed — source on AliExpress (iced-out moissanite watches)
-- supplier_price_usd = NULL for watches until supplier is found
-- ════════════════════════════════════════════════════════════════════

INSERT INTO products (
  slug, name, description, category, price, compare_at_price,
  price_tier, images, stone_type, stone_size, stone_color,
  metal, stock, sku, supplier_sku, is_featured, is_active, tags,
  chain_width_mm, chain_length_in, weight_grams, certificate_type,
  supplier_price_usd
) VALUES

-- ─── EARRINGS (new) ───
('boucles-moissanite-4mm-argent','Boucles d''Oreilles Moissanite 4mm','Puces moissanite VVS 4mm (0.4ct×2) en argent 925. Discret et brillant. Passent le diamond test. Certifiées GRA.','earring',45,59,'entry','[{"url":"/images/products/earrings-4mm.jpg","alt":"Boucles 4mm","position":0}]','moissanite','4mm','D','silver-925',100,'ICK-E-4MM','NUOYA-EARRING-4MM',false,true,ARRAY['boucles','earrings','puces','moissanite','4mm','discret'],null,null,2,'GRA',NULL),
('boucles-moissanite-12mm-argent','Boucles d''Oreilles Moissanite 12mm','Puces moissanite VVS 12mm (6ct×2) en argent 925. Ultra statement. Passent le diamond test. Certifiées GRA.','earring',199,249,'mid','[{"url":"/images/products/earrings-12mm.jpg","alt":"Boucles 12mm","position":0}]','moissanite','12mm','D','silver-925',20,'ICK-E-12MM','NUOYA-EARRING-12MM',false,true,ARRAY['boucles','earrings','puces','moissanite','12mm','ultra'],null,null,8,'GRA',NULL),
('creoles-moissanite-10mm','Créoles Moissanite Iced 10mm','Créoles iced-out 10mm moissanite VVS en argent 925. Le classique revisité. Certifiées GRA.','earring',129,169,'mid','[{"url":"/images/products/earrings-hoop-10mm.jpg","alt":"Créoles 10mm","position":0}]','moissanite','VVS','D','silver-925',35,'ICK-E-H10','NUOYA-HOOP-10MM',true,true,ARRAY['créoles','hoops','earrings','moissanite','10mm'],null,null,5,'GRA',NULL),
('creoles-moissanite-15mm','Créoles Moissanite Iced 15mm','Créoles iced-out 15mm moissanite VVS en argent 925. Statement size. Certifiées GRA.','earring',179,219,'mid','[{"url":"/images/products/earrings-hoop-15mm.jpg","alt":"Créoles 15mm","position":0}]','moissanite','VVS','D','silver-925',25,'ICK-E-H15','NUOYA-HOOP-15MM',false,true,ARRAY['créoles','hoops','earrings','moissanite','15mm'],null,null,7,'GRA',NULL),

-- ─── RINGS (new) ───
('bague-cuban-band-argent','Bague Cuban Band Moissanite','Band ring style cubain en argent 925 serti moissanite VVS tout le tour. Diamond test validé. Tailles 7-11.','ring',89,119,'entry','[{"url":"/images/products/ring-cuban-band.jpg","alt":"Bague Cuban Band","position":0}]','moissanite','VVS','D','silver-925',40,'ICK-R-CUB','NUOYA-RING-CUBAN',false,true,ARRAY['bague','ring','cuban','band','moissanite'],null,null,7,'GRA',NULL),
('bague-tennis-argent','Bague Tennis Moissanite','Bague tennis iced-out moissanite VVS en argent 925. Rangée complète de brillants. Tailles 7-11.','ring',109,139,'mid','[{"url":"/images/products/ring-tennis.jpg","alt":"Bague Tennis","position":0}]','moissanite','VVS','D','silver-925',35,'ICK-R-TEN','NUOYA-RING-TENNIS',true,true,ARRAY['bague','ring','tennis','moissanite','argent'],null,null,6,'GRA',NULL),
('bague-eternite-argent','Bague Éternité Moissanite VVS','Bague éternité full iced-out en argent 925 serti moissanite VVS. Symbole de l''infini. Tailles 7-10.','ring',149,189,'mid','[{"url":"/images/products/ring-eternity.jpg","alt":"Bague Éternité","position":0}]','moissanite','VVS full','D','silver-925',25,'ICK-R-ETR','NUOYA-RING-ETERNITY',false,true,ARRAY['bague','ring','éternité','eternity','moissanite'],null,null,8,'GRA',NULL),
('bague-statement-or','Bague Statement Cluster — Or Gold','Bague statement cluster moissanite VVS plaqué or. Plusieurs pierres, un seul effet. Tailles 7-10.','ring',179,219,'mid','[{"url":"/images/products/ring-statement-gold.jpg","alt":"Bague Statement Or","position":0}]','moissanite','VVS','D','gold-plated',20,'ICK-R-STT','NUOYA-RING-STATEMENT',false,true,ARRAY['bague','ring','statement','cluster','moissanite','or'],null,null,9,'GRA',NULL),
('bague-signet-or','Bague Signet Initiale — Or Gold','Bague chevalière initiale personnalisée en laiton plaqué or serti moissanite VVS. 1 lettre gravée.','ring',129,169,'mid','[{"url":"/images/products/ring-signet-gold.jpg","alt":"Bague Signet Or","position":0}]','moissanite','VVS','D','gold-plated',30,'ICK-R-SIG','NUOYA-RING-SIGNET',false,true,ARRAY['bague','ring','signet','initiale','or','personnalisé'],null,null,10,'GRA',NULL),

-- ─── ANKLETS ───
('chevillere-tennis-3mm-argent','Chevillère Tennis 3mm — Argent 925','Chevillère tennis iced-out 3mm en argent 925 serti moissanite VVS. Taille réglable 23-26cm. Certifiée GRA.','anklet',49,69,'entry','[{"url":"/images/products/anklet-tennis-3mm-silver.jpg","alt":"Chevillère Tennis 3mm","position":0}]','moissanite','VVS','D','silver-925',50,'ICK-ANK-TN3S','CHA003',false,true,ARRAY['chevillère','anklet','tennis','argent','3mm'],3,null,6,'GRA',8.00),
('chevillere-tennis-3mm-or','Chevillère Tennis 3mm — Or Gold','Chevillère tennis iced-out 3mm plaqué or serti moissanite VVS. Taille réglable 23-26cm. Certifiée GRA.','anklet',49,69,'entry','[{"url":"/images/products/anklet-tennis-3mm-gold.jpg","alt":"Chevillère Tennis 3mm Or","position":0}]','moissanite','VVS','D','gold-plated',50,'ICK-ANK-TN3G','CHA003',false,true,ARRAY['chevillère','anklet','tennis','or','3mm'],3,null,6,'GRA',8.00),
('chevillere-tennis-5mm-argent','Chevillère Tennis 5mm — Argent 925','Chevillère tennis iced-out 5mm en argent 925 serti moissanite VVS. Taille réglable 23-26cm. Certifiée GRA.','anklet',59,79,'entry','[{"url":"/images/products/anklet-tennis-5mm-silver.jpg","alt":"Chevillère Tennis 5mm","position":0}]','moissanite','VVS','D','silver-925',40,'ICK-ANK-TN5S','CHA003',false,true,ARRAY['chevillère','anklet','tennis','argent','5mm'],5,null,9,'GRA',10.00),
('chevillere-tennis-5mm-or','Chevillère Tennis 5mm — Or Gold','Chevillère tennis iced-out 5mm plaqué or serti moissanite VVS. Taille réglable 23-26cm. Certifiée GRA.','anklet',59,79,'entry','[{"url":"/images/products/anklet-tennis-5mm-gold.jpg","alt":"Chevillère Tennis 5mm Or","position":0}]','moissanite','VVS','D','gold-plated',40,'ICK-ANK-TN5G','CHA003',false,true,ARRAY['chevillère','anklet','tennis','or','5mm'],5,null,9,'GRA',10.00),
('chevillere-cuban-8mm-argent','Chevillère Cuban 8mm — Argent 925','Chevillère cubaine iced-out 8mm en argent 925 serti moissanite VVS. 25cm. Certifiée GRA.','anklet',79,99,'entry','[{"url":"/images/products/anklet-cuban-8mm-silver.jpg","alt":"Chevillère Cuban 8mm","position":0}]','moissanite','VVS','D','silver-925',30,'ICK-ANK-C8S','CHA295',false,true,ARRAY['chevillère','anklet','cuban','argent','8mm'],8,null,18,'GRA',NULL),
('chevillere-cuban-8mm-or','Chevillère Cuban 8mm — Or Gold','Chevillère cubaine iced-out 8mm plaqué or serti moissanite VVS. 25cm. Certifiée GRA.','anklet',79,99,'entry','[{"url":"/images/products/anklet-cuban-8mm-gold.jpg","alt":"Chevillère Cuban 8mm Or","position":0}]','moissanite','VVS','D','gold-plated',30,'ICK-ANK-C8G','CHA295',false,true,ARRAY['chevillère','anklet','cuban','or','8mm'],8,null,18,'GRA',NULL),

-- ─── WATCHES (20) — source on AliExpress separately ───
('montre-iced-sport-argent','Montre Iced Sport Bezel — Argent','Montre sport cadran noir avec bezel iced-out moissanite VVS. Mouvement quartz. Étanche 30m. Bracelet acier.','watch',149,199,'mid','[{"url":"/images/products/watch-sport-silver.jpg","alt":"Montre Sport Argent","position":0}]','moissanite','VVS bezel','D','stainless-steel',20,'ICK-W-SPT-S',NULL,false,true,ARRAY['montre','watch','sport','iced','argent','quartz'],null,null,120,null,NULL),
('montre-iced-sport-or','Montre Iced Sport Bezel — Or Gold','Montre sport cadran noir avec bezel iced-out moissanite VVS. Plaqué or 18k. Mouvement quartz. Étanche 30m.','watch',149,199,'mid','[{"url":"/images/products/watch-sport-gold.jpg","alt":"Montre Sport Or","position":0}]','moissanite','VVS bezel','D','gold-plated',20,'ICK-W-SPT-G',NULL,false,true,ARRAY['montre','watch','sport','iced','or','quartz'],null,null,120,null,NULL),
('montre-miami-argent','Montre Miami Iced — Argent','Montre style Miami avec bezel full iced-out moissanite VVS. Cadran blanc. Mouvement quartz japonais. 40mm.','watch',199,259,'mid','[{"url":"/images/products/watch-miami-silver.jpg","alt":"Montre Miami Argent","position":0}]','moissanite','VVS full bezel','D','silver-925',15,'ICK-W-MIA-S',NULL,true,true,ARRAY['montre','watch','miami','iced','argent'],null,null,130,null,NULL),
('montre-miami-or','Montre Miami Iced — Or Gold','Montre style Miami avec bezel full iced-out moissanite VVS. Cadran blanc. Plaqué or 18k. 40mm.','watch',199,259,'mid','[{"url":"/images/products/watch-miami-gold.jpg","alt":"Montre Miami Or","position":0}]','moissanite','VVS full bezel','D','gold-plated',15,'ICK-W-MIA-G',NULL,true,true,ARRAY['montre','watch','miami','iced','or'],null,null,130,null,NULL),
('montre-royal-40mm-argent','Montre Royal Iced 40mm — Argent','Montre Royal style avec bezel + bracelet iced-out moissanite VVS. Argent 925. Mouvement quartz. 40mm.','watch',299,379,'premium','[{"url":"/images/products/watch-royal-silver.jpg","alt":"Montre Royal Argent","position":0}]','moissanite','VVS','D','silver-925',12,'ICK-W-ROY-S',NULL,false,true,ARRAY['montre','watch','royal','iced','argent','premium'],null,null,145,null,NULL),
('montre-royal-40mm-or','Montre Royal Iced 40mm — Or Gold','Montre Royal style avec bezel + bracelet iced-out moissanite VVS. Plaqué or 18k. Mouvement quartz. 40mm.','watch',299,379,'premium','[{"url":"/images/products/watch-royal-gold.jpg","alt":"Montre Royal Or","position":0}]','moissanite','VVS','D','gold-plated',12,'ICK-W-ROY-G',NULL,false,true,ARRAY['montre','watch','royal','iced','or','premium'],null,null,145,null,NULL),
('montre-submariner-argent','Montre Submariner Style Iced — Argent','Montre submariner iced-out moissanite VVS. Lunette full iced. Argent. Mouvement automatique. 42mm.','watch',349,449,'premium','[{"url":"/images/products/watch-sub-silver.jpg","alt":"Montre Sub Argent","position":0}]','moissanite','VVS bezel','D','silver-925',10,'ICK-W-SUB-S',NULL,false,true,ARRAY['montre','watch','submariner','iced','argent'],null,null,155,null,NULL),
('montre-submariner-or','Montre Submariner Style Iced — Or Gold','Montre submariner iced-out moissanite VVS. Lunette full iced. Plaqué or 18k. Mouvement automatique. 42mm.','watch',349,449,'premium','[{"url":"/images/products/watch-sub-gold.jpg","alt":"Montre Sub Or","position":0}]','moissanite','VVS bezel','D','gold-plated',10,'ICK-W-SUB-G',NULL,true,true,ARRAY['montre','watch','submariner','iced','or'],null,null,155,null,NULL),
('montre-chronograph-argent','Montre Chronograph Iced — Argent','Chronographe iced-out moissanite VVS. 3 cadrans, bezel full stones. Argent. 42mm.','watch',299,379,'premium','[{"url":"/images/products/watch-chrono-silver.jpg","alt":"Montre Chrono Argent","position":0}]','moissanite','VVS','D','silver-925',10,'ICK-W-CHR-S',NULL,false,true,ARRAY['montre','watch','chronograph','iced','argent'],null,null,150,null,NULL),
('montre-chronograph-or','Montre Chronograph Iced — Or Gold','Chronographe iced-out moissanite VVS. 3 cadrans, bezel full stones. Plaqué or 18k. 42mm.','watch',349,439,'premium','[{"url":"/images/products/watch-chrono-gold.jpg","alt":"Montre Chrono Or","position":0}]','moissanite','VVS','D','gold-plated',8,'ICK-W-CHR-G',NULL,false,true,ARRAY['montre','watch','chronograph','iced','or'],null,null,150,null,NULL),
('montre-presidential-argent','Montre Presidential Iced — Argent 925','Montre Presidential full iced-out moissanite VVS en argent 925. Bezel + bracelet stones. 40mm.','watch',499,629,'premium','[{"url":"/images/products/watch-pres-silver.jpg","alt":"Montre Presidential Argent","position":0}]','moissanite','VVS full','D','silver-925',8,'ICK-W-PRE-S',NULL,false,true,ARRAY['montre','watch','presidential','iced','argent','luxury'],null,null,160,null,NULL),
('montre-presidential-or','Montre Presidential Iced — Or Gold','Montre Presidential full iced-out moissanite VVS plaqué or 18k. Bezel + bracelet stones. 40mm.','watch',549,699,'premium','[{"url":"/images/products/watch-pres-gold.jpg","alt":"Montre Presidential Or","position":0}]','moissanite','VVS full','D','gold-plated',8,'ICK-W-PRE-G',NULL,true,true,ARRAY['montre','watch','presidential','iced','or','luxury'],null,null,160,null,NULL),
('montre-baguette-argent','Montre Baguette Full Ice — Argent','Montre full iced-out pierres baguettes moissanite VVS en argent 925. Pièce art. 38mm.','watch',449,569,'premium','[{"url":"/images/products/watch-bag-silver.jpg","alt":"Montre Baguette Argent","position":0}]','moissanite','baguette VVS','D','silver-925',6,'ICK-W-BAG-S',NULL,false,true,ARRAY['montre','watch','baguette','iced','argent','statement'],null,null,155,null,NULL),
('montre-baguette-or','Montre Baguette Full Ice — Or Gold','Montre full iced-out pierres baguettes moissanite VVS plaqué or 18k. Pièce art. 38mm.','watch',499,629,'premium','[{"url":"/images/products/watch-bag-gold.jpg","alt":"Montre Baguette Or","position":0}]','moissanite','baguette VVS','D','gold-plated',6,'ICK-W-BAG-G',NULL,false,true,ARRAY['montre','watch','baguette','iced','or','statement'],null,null,155,null,NULL),
('montre-day-date-or','Montre Day-Date Style Full Ice — Or','Montre Day-Date style full iced-out moissanite VVS plaqué or 18k. Cadran chiffres romains. 40mm.','watch',599,749,'luxury','[{"url":"/images/products/watch-daydate-gold.jpg","alt":"Montre Day-Date Or","position":0}]','moissanite','VVS full','D','gold-plated',5,'ICK-W-DAY-G',NULL,true,true,ARRAY['montre','watch','day-date','iced','or','luxury'],null,null,165,null,NULL),
('montre-bust-down-argent','Montre Bust Down Full Ice — Argent','Montre Bust Down intégralement couverte moissanite VVS en argent 925. La quintessence. 41mm.','watch',899,1099,'luxury','[{"url":"/images/products/watch-bust-silver.jpg","alt":"Montre Bust Down Argent","position":0}]','moissanite','VVS full','D','silver-925',4,'ICK-W-BUS-S',NULL,false,true,ARRAY['montre','watch','bust-down','full-ice','argent','ultra'],null,null,175,null,NULL),
('montre-bust-down-or','Montre Bust Down Full Ice — Or Gold','Montre Bust Down intégralement couverte moissanite VVS plaqué or 18k. La quintessence. 41mm.','watch',999,1249,'luxury','[{"url":"/images/products/watch-bust-gold.jpg","alt":"Montre Bust Down Or","position":0}]','moissanite','VVS full','D','gold-plated',4,'ICK-W-BUS-G',NULL,true,true,ARRAY['montre','watch','bust-down','full-ice','or','ultra'],null,null,175,null,NULL),
('montre-royal-ap-argent','Montre Royal Style Full Ice — Argent','Montre Royal Octagon style full iced-out moissanite VVS en argent 925. Bracelet intégré. 41mm.','watch',1099,1349,'ultra','[{"url":"/images/products/watch-ap-silver.jpg","alt":"Montre Royal Style Argent","position":0}]','moissanite','VVS full','D','silver-925',3,'ICK-W-APR-S',NULL,false,true,ARRAY['montre','watch','royal-ap','full-ice','argent','ultra','rare'],null,null,180,null,NULL),
('montre-royal-ap-or','Montre Royal Style Full Ice — Or 18k','Montre Royal Octagon style full iced-out moissanite VVS plaqué or 18k. Bracelet intégré. 41mm.','watch',1299,1599,'ultra','[{"url":"/images/products/watch-ap-gold.jpg","alt":"Montre Royal Style Or","position":0}]','moissanite','VVS full','D','gold-plated',3,'ICK-W-APR-G',NULL,true,true,ARRAY['montre','watch','royal-ap','full-ice','or','ultra','rare'],null,null,180,null,NULL),
('montre-ultra-ice-premium','Montre Ultra Ice Premium — Or 18k','La montre ultime. Full bust down moissanite VVS grade D sur or 18k véritable. Pièce de collection. Édition limitée.','watch',1499,1849,'ultra','[{"url":"/images/products/watch-ultra-gold.jpg","alt":"Montre Ultra Ice Premium","position":0}]','moissanite','VVS full','D','18k-gold',2,'ICK-W-ULT-G',NULL,true,true,ARRAY['montre','watch','ultra','full-ice','or-18k','collector','édition-limitée'],null,null,190,null,NULL);
