-- ════════════════════════════════════════════════════════════════════
-- ICEKEY — Catalog expansion Part 2: Bracelets + Pendants
-- ════════════════════════════════════════════════════════════════════

INSERT INTO products (
  slug, name, description, category, price, compare_at_price,
  price_tier, images, stone_type, stone_size, stone_color,
  metal, stock, sku, supplier_sku, is_featured, is_active, tags,
  chain_width_mm, chain_length_in, weight_grams, certificate_type,
  supplier_price_usd
) VALUES

-- ─── BRACELETS ───
('bracelet-tennis-4mm-argent','Bracelet Tennis 4mm — Argent 925','Bracelet tennis iced-out 4mm en argent 925 serti moissanite VVS. Taille universelle 19cm. Certifié GRA.','bracelet',39,59,'entry','[{"url":"/images/products/bracelet-tennis-4mm-silver.jpg","alt":"Bracelet Tennis 4mm Argent","position":0}]','moissanite','VVS','D','silver-925',80,'ICK-BR-TN4S','CHA003',false,true,ARRAY['bracelet','tennis','iced-out','argent','4mm'],4,null,8,'GRA',6.00),
('bracelet-tennis-4mm-or','Bracelet Tennis 4mm — Or Gold','Bracelet tennis iced-out 4mm plaqué or serti moissanite VVS. Taille universelle 19cm. Certifié GRA.','bracelet',39,59,'entry','[{"url":"/images/products/bracelet-tennis-4mm-gold.jpg","alt":"Bracelet Tennis 4mm Or","position":0}]','moissanite','VVS','D','gold-plated',80,'ICK-BR-TN4G','CHA003',false,true,ARRAY['bracelet','tennis','iced-out','or','gold','4mm'],4,null,8,'GRA',6.00),
('bracelet-tennis-6mm-argent','Bracelet Tennis 6mm — Argent 925','Bracelet tennis iced-out 6mm en argent 925 serti moissanite VVS. Taille universelle 19cm. Certifié GRA.','bracelet',49,69,'entry','[{"url":"/images/products/bracelet-tennis-6mm-silver.jpg","alt":"Bracelet Tennis 6mm Argent","position":0}]','moissanite','VVS','D','silver-925',70,'ICK-BR-TN6S','CHA003',false,true,ARRAY['bracelet','tennis','iced-out','argent','6mm'],6,null,11,'GRA',8.00),
('bracelet-tennis-6mm-or','Bracelet Tennis 6mm — Or Gold','Bracelet tennis iced-out 6mm plaqué or serti moissanite VVS. Taille universelle 19cm. Certifié GRA.','bracelet',49,69,'entry','[{"url":"/images/products/bracelet-tennis-6mm-gold.jpg","alt":"Bracelet Tennis 6mm Or","position":0}]','moissanite','VVS','D','gold-plated',70,'ICK-BR-TN6G','CHA003',true,true,ARRAY['bracelet','tennis','iced-out','or','gold','6mm'],6,null,11,'GRA',8.00),
('bracelet-cuban-10mm-argent','Bracelet Cuban 10mm — Argent 925','Bracelet cubain iced-out 10mm en argent 925 serti moissanite VVS. 20cm. Certifié GRA.','bracelet',99,129,'mid','[{"url":"/images/products/bracelet-cuban-10mm-silver.jpg","alt":"Bracelet Cuban 10mm Argent","position":0}]','moissanite','VVS','D','silver-925',50,'ICK-BR-C10S','CHA288',false,true,ARRAY['bracelet','cuban','iced-out','argent','10mm'],10,null,32,'GRA',20.00),
('bracelet-cuban-10mm-or','Bracelet Cuban 10mm — Or Gold','Bracelet cubain iced-out 10mm plaqué or serti moissanite VVS. 20cm. Certifié GRA.','bracelet',99,129,'mid','[{"url":"/images/products/bracelet-cuban-10mm-gold.jpg","alt":"Bracelet Cuban 10mm Or","position":0}]','moissanite','VVS','D','gold-plated',50,'ICK-BR-C10G','CHA288',true,true,ARRAY['bracelet','cuban','iced-out','or','gold','10mm'],10,null,32,'GRA',20.00),
('bracelet-cuban-12mm-argent','Bracelet Cuban 12mm — Argent 925','Bracelet cubain iced-out 12mm en argent 925 serti moissanite VVS. 20cm. Certifié GRA.','bracelet',119,149,'mid','[{"url":"/images/products/bracelet-cuban-12mm-silver.jpg","alt":"Bracelet Cuban 12mm Argent","position":0}]','moissanite','VVS','D','silver-925',40,'ICK-BR-C12S','CHA296',false,true,ARRAY['bracelet','cuban','iced-out','argent','12mm'],12,null,40,'GRA',25.00),
('bracelet-cuban-12mm-or','Bracelet Cuban 12mm — Or Gold','Bracelet cubain iced-out 12mm plaqué or serti moissanite VVS. 20cm. Certifié GRA.','bracelet',119,149,'mid','[{"url":"/images/products/bracelet-cuban-12mm-gold.jpg","alt":"Bracelet Cuban 12mm Or","position":0}]','moissanite','VVS','D','gold-plated',40,'ICK-BR-C12G','CHA296',false,true,ARRAY['bracelet','cuban','iced-out','or','gold','12mm'],12,null,40,'GRA',25.00),
('bracelet-cuban-15mm-argent','Bracelet Cuban 15mm — Argent 925','Bracelet cubain statement 15mm en argent 925 serti moissanite VVS. 20cm. Certifié GRA.','bracelet',129,169,'mid','[{"url":"/images/products/bracelet-cuban-15mm-silver.jpg","alt":"Bracelet Cuban 15mm Argent","position":0}]','moissanite','VVS','D','silver-925',30,'ICK-BR-C15S','CHA021',false,true,ARRAY['bracelet','cuban','iced-out','argent','15mm'],15,null,52,'GRA',32.70),
('bracelet-cuban-15mm-or','Bracelet Cuban 15mm — Or Gold','Bracelet cubain statement 15mm plaqué or serti moissanite VVS. 20cm. Certifié GRA.','bracelet',129,169,'mid','[{"url":"/images/products/bracelet-cuban-15mm-gold.jpg","alt":"Bracelet Cuban 15mm Or","position":0}]','moissanite','VVS','D','gold-plated',30,'ICK-BR-C15G','CHA021',true,true,ARRAY['bracelet','cuban','iced-out','or','gold','15mm'],15,null,52,'GRA',32.70),
('bracelet-cuban-18mm-argent','Bracelet Cuban 18mm — Argent 925','Bracelet cubain XXL 18mm en argent 925 serti moissanite VVS. 20cm. Certifié GRA.','bracelet',149,189,'mid','[{"url":"/images/products/bracelet-cuban-18mm-silver.jpg","alt":"Bracelet Cuban 18mm Argent","position":0}]','moissanite','VVS','D','silver-925',25,'ICK-BR-C18S','CHA025',false,true,ARRAY['bracelet','cuban','iced-out','argent','18mm'],18,null,65,'GRA',43.00),
('bracelet-cuban-18mm-or','Bracelet Cuban 18mm — Or Gold','Bracelet cubain XXL 18mm plaqué or serti moissanite VVS. 20cm. Certifié GRA.','bracelet',149,189,'mid','[{"url":"/images/products/bracelet-cuban-18mm-gold.jpg","alt":"Bracelet Cuban 18mm Or","position":0}]','moissanite','VVS','D','gold-plated',25,'ICK-BR-C18G','CHA025',false,true,ARRAY['bracelet','cuban','iced-out','or','gold','18mm'],18,null,65,'GRA',43.00),

-- ─── PENDANTS ───
('pendentif-tete-lion-or','Pendentif Tête de Lion VVS — Or Gold','Lion head iced-out full moissanite VVS en laiton plaqué or. Pièce emblématique. Certifiée GRA.','pendant',199,249,'mid','[{"url":"/images/products/pendant-lion-gold.jpg","alt":"Tête de lion or","position":0}]','moissanite','VVS full','D','gold-plated',20,'ICK-P-LIO-G',NULL,true,true,ARRAY['lion','pendentif','iced-out','or','gold','animal'],null,null,20,'GRA',NULL),
('pendentif-tete-lion-argent','Pendentif Tête de Lion VVS — Argent 925','Lion head iced-out full moissanite VVS en argent 925. Pièce emblématique. Certifiée GRA.','pendant',179,229,'mid','[{"url":"/images/products/pendant-lion-silver.jpg","alt":"Tête de lion argent","position":0}]','moissanite','VVS full','D','silver-925',20,'ICK-P-LIO-S',NULL,false,true,ARRAY['lion','pendentif','iced-out','argent','animal'],null,null,18,'GRA',NULL),
('pendentif-dollar-sign-or','Pendentif Dollar Sign VVS — Or Gold','Dollar sign iced-out moissanite VVS plaqué or. Le symbole du flex. Certifiée GRA.','pendant',159,199,'mid','[{"url":"/images/products/pendant-dollar-gold.jpg","alt":"Dollar sign or","position":0}]','moissanite','VVS','D','gold-plated',25,'ICK-P-DOL-G',NULL,false,true,ARRAY['dollar','pendentif','iced-out','or','hip-hop'],null,null,12,'GRA',NULL),
('pendentif-dollar-sign-argent','Pendentif Dollar Sign VVS — Argent 925','Dollar sign iced-out moissanite VVS en argent 925. Le symbole du flex. Certifiée GRA.','pendant',139,179,'mid','[{"url":"/images/products/pendant-dollar-silver.jpg","alt":"Dollar sign argent","position":0}]','moissanite','VVS','D','silver-925',25,'ICK-P-DOL-S',NULL,false,true,ARRAY['dollar','pendentif','iced-out','argent','hip-hop'],null,null,10,'GRA',NULL),
('pendentif-couronne-or','Pendentif Couronne VVS — Or Gold','Couronne royale iced-out moissanite VVS plaqué or. Pour ceux qui portent la couronne. Certifiée GRA.','pendant',199,249,'mid','[{"url":"/images/products/pendant-crown-gold.jpg","alt":"Couronne or","position":0}]','moissanite','VVS full','D','gold-plated',20,'ICK-P-CRW-G',NULL,true,true,ARRAY['couronne','crown','pendentif','iced-out','or','royauté'],null,null,14,'GRA',NULL),
('pendentif-couronne-argent','Pendentif Couronne VVS — Argent 925','Couronne royale iced-out moissanite VVS en argent 925. Pour ceux qui portent la couronne. Certifiée GRA.','pendant',179,219,'mid','[{"url":"/images/products/pendant-crown-silver.jpg","alt":"Couronne argent","position":0}]','moissanite','VVS full','D','silver-925',20,'ICK-P-CRW-S',NULL,false,true,ARRAY['couronne','crown','pendentif','iced-out','argent','royauté'],null,null,12,'GRA',NULL),
('pendentif-praying-hands-argent','Pendentif Praying Hands VVS — Argent 925','Mains en prière full iced-out moissanite VVS en argent 925. Foi et flexion. Certifiée GRA.','pendant',149,189,'mid','[{"url":"/images/products/pendant-pray-silver.jpg","alt":"Praying hands argent","position":0}]','moissanite','VVS','D','silver-925',30,'ICK-P-PRY-S',NULL,false,true,ARRAY['praying','foi','pendentif','iced-out','argent','religieux'],null,null,16,'GRA',NULL),
('pendentif-evil-eye-argent','Pendentif Evil Eye VVS — Argent 925','Evil eye iced-out moissanite VVS en argent 925. Protection et style. Certifiée GRA.','pendant',99,129,'entry','[{"url":"/images/products/pendant-evil-eye-silver.jpg","alt":"Evil eye argent","position":0}]','moissanite','VVS','D','silver-925',40,'ICK-P-EVE-S',NULL,false,true,ARRAY['evil-eye','pendentif','iced-out','argent','protection'],null,null,6,'GRA',NULL),
('pendentif-evil-eye-or','Pendentif Evil Eye VVS — Or Gold','Evil eye iced-out moissanite VVS plaqué or. Protection et style. Certifiée GRA.','pendant',119,149,'mid','[{"url":"/images/products/pendant-evil-eye-gold.jpg","alt":"Evil eye or","position":0}]','moissanite','VVS','D','gold-plated',40,'ICK-P-EVE-G',NULL,false,true,ARRAY['evil-eye','pendentif','iced-out','or','protection'],null,null,6,'GRA',NULL),
('pendentif-scorpion-or','Pendentif Scorpion VVS — Or Gold','Scorpion full iced-out moissanite VVS plaqué or. Pièce rare et statement. Certifiée GRA.','pendant',229,289,'premium','[{"url":"/images/products/pendant-scorpion-gold.jpg","alt":"Scorpion or","position":0}]','moissanite','VVS full','D','gold-plated',15,'ICK-P-SCO-G',NULL,false,true,ARRAY['scorpion','pendentif','iced-out','or','zodiac','rare'],null,null,22,'GRA',NULL),
('pendentif-ancre-argent','Pendentif Ancre VVS — Argent 925','Ancre marine iced-out moissanite VVS en argent 925. Le classique revisité. Certifiée GRA.','pendant',149,189,'mid','[{"url":"/images/products/pendant-anchor-silver.jpg","alt":"Ancre argent","position":0}]','moissanite','VVS','D','silver-925',30,'ICK-P-ANC-S',NULL,false,true,ARRAY['ancre','anchor','pendentif','iced-out','argent'],null,null,12,'GRA',NULL),
('pendentif-ancre-or','Pendentif Ancre VVS — Or Gold','Ancre marine iced-out moissanite VVS plaqué or. Le classique revisité. Certifiée GRA.','pendant',169,209,'mid','[{"url":"/images/products/pendant-anchor-gold.jpg","alt":"Ancre or","position":0}]','moissanite','VVS','D','gold-plated',25,'ICK-P-ANC-G',NULL,false,true,ARRAY['ancre','anchor','pendentif','iced-out','or'],null,null,12,'GRA',NULL),
('pendentif-africa-or','Pendentif Map of Africa VVS — Or Gold','Carte de l''Afrique iced-out moissanite VVS plaqué or. Roots. Certifiée GRA.','pendant',179,219,'mid','[{"url":"/images/products/pendant-africa-gold.jpg","alt":"Africa map or","position":0}]','moissanite','VVS','D','gold-plated',20,'ICK-P-AFR-G',NULL,true,true,ARRAY['afrique','africa','pendentif','iced-out','or','identité'],null,null,14,'GRA',NULL),
('pendentif-nameplate-custom','Pendentif Nameplate Personnalisé','Plaque prénom sur mesure en argent 925 serti moissanite VVS. Jusqu''à 8 caractères. Délai 5-7 jours. Certifiée GRA.','pendant',199,249,'mid','[{"url":"/images/products/pendant-nameplate.jpg","alt":"Nameplate custom","position":0}]','moissanite','VVS','D','silver-925',15,'ICK-P-NAM',NULL,true,true,ARRAY['prénom','nameplate','personnalisé','pendentif','custom'],null,null,10,'GRA',NULL);
