-- ──────────────────────────────────────────────
-- ICEKEY · Product Seed (sample — 30 SKUs)
-- Run full seed via scripts/generate-products.ts
-- ──────────────────────────────────────────────

INSERT INTO products (slug, name, description, category, price, price_tier, images, stone_type, stone_size, stone_color, metal, stock, sku, is_featured, tags) VALUES

-- RINGS · Entry (< €100)
('bague-moissanite-solitaire-argent-3mm',   'Solitaire Moissanite Argent 3mm',   'Bague solitaire en argent 925 avec moissanite ronde de 3mm. Taille D, clarté VVS.',  'ring',     79,  'entry',   '[{"url":"/images/products/ring-001.jpg","alt":"Solitaire 3mm argent","position":0}]', 'moissanite', '3mm',   'D', 'silver-925', 20, 'ICK-R-001', true,  ARRAY['solitaire','argent','classique']),
('bague-moissanite-solitaire-argent-5mm',   'Solitaire Moissanite Argent 5mm',   'Bague solitaire en argent 925 avec moissanite ronde de 5mm (0.5ct). Certifiée GRA.', 'ring',     139, 'mid',     '[{"url":"/images/products/ring-002.jpg","alt":"Solitaire 5mm argent","position":0}]', 'moissanite', '5mm',   'D', 'silver-925', 15, 'ICK-R-002', true,  ARRAY['solitaire','argent']),
('bague-moissanite-halo-or-14k',            'Halo Moissanite Or 14k',            'Bague halo en or 14 carats avec moissanite centrale 6.5mm entourée de pavé.',         'ring',     349, 'premium', '[{"url":"/images/products/ring-003.jpg","alt":"Halo or 14k","position":0}]',         'moissanite', '6.5mm', 'D', 'gold-14k',   10, 'ICK-R-003', true,  ARRAY['halo','or','pavé']),
('bague-moissanite-eternity-or-18k',        'Eternity Band Or 18k',              'Alliance eternity en or 18 carats avec moissanites de 3mm tout le tour.',              'ring',     589, 'luxury',  '[{"url":"/images/products/ring-004.jpg","alt":"Eternity or 18k","position":0}]',     'moissanite', '3mm',   'D', 'gold-18k',   5,  'ICK-R-004', false, ARRAY['eternity','alliance','or']),
('bague-moissanite-pear-solitaire-or-14k',  'Poire Solitaire Or 14k',            'Bague solitaire taille poire 8x5mm en or 14k. Élégance pure, coupe brillante.',       'ring',     279, 'premium', '[{"url":"/images/products/ring-005.jpg","alt":"Poire or 14k","position":0}]',        'moissanite', '8x5mm', 'D', 'gold-14k',   8,  'ICK-R-005', true,  ARRAY['poire','solitaire','or']),

-- NECKLACES · Entry to Mid
('collier-pendentif-moissanite-ronde-argent', 'Pendentif Ronde Argent',           'Collier fin en argent 925 avec pendentif moissanite ronde 6.5mm (1ct).',             'necklace', 99,  'entry',   '[{"url":"/images/products/neck-001.jpg","alt":"Pendentif ronde argent","position":0}]', 'moissanite', '6.5mm', 'D', 'silver-925', 25, 'ICK-N-001', true,  ARRAY['pendentif','argent','ronde']),
('collier-solitaire-or-14k-6mm',            'Collier Solitaire Or 14k 6mm',      'Chaîne en or 14k avec solitaire moissanite 6mm sur chaîne réglable 40–45cm.',         'necklace', 229, 'mid',     '[{"url":"/images/products/neck-002.jpg","alt":"Solitaire or 14k","position":0}]',    'moissanite', '6mm',   'D', 'gold-14k',   12, 'ICK-N-002', true,  ARRAY['solitaire','or','collier']),
('collier-tennis-moissanite-argent',        'Collier Tennis Moissanite',         'Collier tennis en argent 925 avec 3mm moissanites rondes tout le tour.',               'necklace', 189, 'mid',     '[{"url":"/images/products/neck-003.jpg","alt":"Tennis argent","position":0}]',       'moissanite', '3mm',   'D', 'silver-925', 18, 'ICK-N-003', false, ARRAY['tennis','argent']),
('collier-drop-poire-or-18k',               'Drop Pendentif Poire Or 18k',       'Pendentif goutte taille poire 10x7mm en or 18k. Certifié GRA. Chaîne 45cm incluse.', 'necklace', 649, 'luxury',  '[{"url":"/images/products/neck-004.jpg","alt":"Drop poire or 18k","position":0}]',   'moissanite', '10x7mm','D', 'gold-18k',   4,  'ICK-N-004', true,  ARRAY['drop','poire','or','luxe']),

-- PENDANTS
('pendentif-croix-moissanite-argent',       'Croix Moissanite Argent',           'Pendentif croix en argent 925 avec moissanites pavé. Design épuré et moderne.',       'pendant',  129, 'mid',     '[{"url":"/images/products/pend-001.jpg","alt":"Croix argent","position":0}]',       'moissanite', '2mm',   'D', 'silver-925', 20, 'ICK-P-001', false, ARRAY['croix','pavé','argent']),
('pendentif-coeur-moissanite-or-14k',       'Cœur Moissanite Or 14k',            'Pendentif cœur en or 14k avec moissanite centrale. Idéal cadeau Saint-Valentin.',     'pendant',  249, 'premium', '[{"url":"/images/products/pend-002.jpg","alt":"Cœur or 14k","position":0}]',       'moissanite', '6mm',   'D', 'gold-14k',   10, 'ICK-P-002', true,  ARRAY['coeur','or','cadeau']),
('pendentif-custom-sur-mesure',             'Pendentif Sur Mesure',              'Créez votre pendentif unique. Choisissez la pierre, le métal, la gravure.',            'pendant',  149, 'mid',     '[{"url":"/images/products/pend-custom.jpg","alt":"Sur mesure","position":0}]',     'moissanite', NULL,    'D', 'silver-925', 99, 'ICK-P-CUSTOM', true, ARRAY['sur-mesure','personnalisé']),

-- BRACELETS
('bracelet-tennis-moissanite-argent-18cm',  'Tennis Moissanite Argent 18cm',     'Bracelet tennis en argent 925 avec moissanites 4mm, longueur ajustable 17–19cm.',     'bracelet', 179, 'mid',     '[{"url":"/images/products/brac-001.jpg","alt":"Tennis argent","position":0}]',      'moissanite', '4mm',   'D', 'silver-925', 14, 'ICK-B-001', true,  ARRAY['tennis','argent','bracelet']),
('bracelet-jonc-moissanite-or-14k',         'Jonc Moissanite Or 14k',            'Bracelet jonc en or 14k avec 5 moissanites 5mm. Ouverture réglable.',                 'bracelet', 449, 'luxury',  '[{"url":"/images/products/brac-002.jpg","alt":"Jonc or 14k","position":0}]',       'moissanite', '5mm',   'D', 'gold-14k',   6,  'ICK-B-002', false, ARRAY['jonc','or','luxe']),

-- EARRINGS
('boucles-clous-moissanite-argent-5mm',     'Clous Moissanite Argent 5mm',       'Boucles d'oreilles clous en argent 925 avec moissanites rondes 5mm (0.5ct/pierre).',  'earring',  89,  'entry',   '[{"url":"/images/products/ear-001.jpg","alt":"Clous argent 5mm","position":0}]',   'moissanite', '5mm',   'D', 'silver-925', 22, 'ICK-E-001', true,  ARRAY['clous','argent','classique']),
('boucles-pendantes-goutte-or-14k',         'Pendantes Goutte Or 14k',           'Boucles d'oreilles pendantes en or 14k, moissanite taille poire 8x5mm.',               'earring',  319, 'premium', '[{"url":"/images/products/ear-002.jpg","alt":"Pendantes or 14k","position":0}]',  'moissanite', '8x5mm', 'D', 'gold-14k',   8,  'ICK-E-002', false, ARRAY['pendantes','or','poire']),
('boucles-halo-moissanite-or-18k',          'Halo Moissanite Or 18k',            'Boucles halo en or 18k. Moissanite centrale 6mm entourée de pavé. Éclat maximal.',    'earring',  599, 'luxury',  '[{"url":"/images/products/ear-003.jpg","alt":"Halo or 18k","position":0}]',       'moissanite', '6mm',   'D', 'gold-18k',   4,  'ICK-E-003', true,  ARRAY['halo','or','luxe']),

-- ULTRA tier
('bague-moissanite-collector-platinum-3ct', 'Solitaire Collector Platine 3ct',   'Bague solitaire en platine avec moissanite ronde 9mm (3ct). Certificat GRA Premium.', 'ring',     1290,'ultra',   '[{"url":"/images/products/ring-ultra-001.jpg","alt":"Collector platine 3ct","position":0}]', 'moissanite', '9mm', 'D', 'platinum', 2, 'ICK-R-ULTRA-001', true, ARRAY['collector','platine','ultra','3ct']),
('collier-riviere-platine-moissanite',      'Rivière Platine Moissanite',        'Collier rivière en platine avec 11 moissanites rondes de 6.5mm (1ct chacune).',       'necklace', 2490,'ultra',   '[{"url":"/images/products/neck-ultra-001.jpg","alt":"Rivière platine","position":0}]',       'moissanite', '6.5mm','D', 'platinum', 1, 'ICK-N-ULTRA-001', true, ARRAY['rivière','platine','ultra','collector']);
